version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/app  
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development  
    depends_on:
      - db  

  db:
    image: nouchka/sqlite3:latest  
    volumes:
      - sqlite_data:/data 

volumes:
  sqlite_data:
